### ISSUE TITLE
Buck Converter Voltage Rating

### ISSUE THREAD

**Issue by cgalford** [robin7331/IKEA-Hackant#4]
Have you put a scope or meter on the power line ("24V")? The power supply rests at ~24V but then ramps to ~35V when the desk is moving. My power supply went out so I've been trying to find an off the shelf solution. A generic 24V power supply results in very slow desk movement and a generic 36V matches the proper speed but without the slower ramp up.  It looks like you are using a MP1584EN converter which is rated to 28V input.

**Comment by robin7331** [comment]
Wow. Two years late but finally found this issue :)
Thats probably the reason why my buck converter died relatively soon.
Did not even think about measuring the voltage when this thing was running.
Kinda funny to have a system designed like that.. ?

Thanks for the info!
