### ISSUE TITLE
No readings

### ISSUE THREAD

**Issue by prk3** [robin7331/IKEA-Hackant#7]
Hi. I am trying to hack my Bekant desk, but my Arduino isn't capturing any LIN frames. I tried connecting the wire, that normally goes to digital pin 2, to analog pin 2 and see what readings I would get. It turns out it constantly reads value 8 (sometimes 9). I think the voltage on LIN wire is too low to trigger frame detection. Do you have an idea what might be the cause? 
 
![img_20190130_234755](https://user-images.githubusercontent.com/16927151/52019185-48476b80-24ed-11e9-87c5-2c477237e09a.jpg)
![img_20190130_234938](https://user-images.githubusercontent.com/16927151/52019186-48476b80-24ed-11e9-99dd-26b22598bde9.jpg)
![img_20190130_234955](https://user-images.githubusercontent.com/16927151/52019187-48e00200-24ed-11e9-952f-7eecf508f070.jpg)

I forgot to mention. The stock controller works fine, I can move the table without any problems.

**Comment by robin7331** [comment]
Are you sure you picked the right pin for your ground connection?

**Comment by prk3** [comment]
I didn't want to remove this big white connector completely and I after poking around with a multimeter I came to a conclusion that these three spots are all connected with each other.

![image](https://user-images.githubusercontent.com/16927151/52041290-422bac00-253a-11e9-8dd1-2e101f3c267c.png)

I get exactly the same result from all 3, so it probably isn't the problem.

**Comment by prk3** [comment]
I either damaged the original controller while trying to hack it or did not consider different order of pins on the transistor I used (yours has EBC layout, mine had ECB).
At the end I decided to replace the controller completely. You can check it out [here](https://github.com/trainman419/bekant) (pictures and 3d case are yet to be added).
Thanks a lot for help!
